# Generated by Django 3.1 on 2020-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('avistado', 'Avistado'), ('retenido', 'Retenido'), ('otro', 'Otro')], default='', max_length=12),
        ),
    ]
