# Generated by Django 3.1 on 2020-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200930_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
