# Generated by Django 3.1 on 2020-10-02 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='reports')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('report_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
    ]
