# Generated by Django 3.1 on 2020-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='datauri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
