# Generated by Django 3.1 on 2020-10-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reportimage_datauri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='datauri',
        ),
    ]
