# Generated by Django 3.1 on 2021-01-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201005_0356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
