# Generated by Django 3.1 on 2021-01-24 20:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[600, 600], upload_to='animals'),
        ),
    ]
