# Generated by Django 3.1 on 2023-06-19 20:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210124_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('specie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=6)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.ImageField(upload_to='pet_pictures/')),
                ('allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='who_sent',
        ),
        migrations.AlterField(
            model_name='report',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[600, 600], upload_to='animals'),
        ),
    ]
