# Generated by Django 3.1 on 2023-06-16 19:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210124_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='who_sent',
        ),
        migrations.AlterField(
            model_name='report',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[600, 600], upload_to='animals'),
        ),
    ]
