# Generated by Django 3.2 on 2023-06-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230619_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petadoptionmodel',
            name='title',
        ),
    ]
