# Generated by Django 3.2 on 2023-06-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_petadoptionmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
