# Generated by Django 3.2 on 2023-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_report_is_tweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoptionmodel',
            name='state',
            field=models.CharField(default='Central', max_length=100),
            preserve_default=False,
        ),
    ]
